### ISSUE TITLE
الكوردات

### ISSUE THREAD

**Issue by MalekBakary** [MalekBakary/App#1]
1- لما تكبس عالكورد بصفحة الترنيمة يطلع صفحتين 1 و 2 بس الصورتين نفس الشي

2- صورة الكوردات المستعملة مانها أفضل الشي! ممكن نشوف شي اوضح؟ كتير عريضة الخطوط فيها

**Comment by MalekBakary** [comment]
The line thickness is better now. Can you make the chord image bigger to fill up the popup screen?

**Comment by eliasalbro95** [comment]
![Simulator Screen Shot - iPhone 14 Pro Max - 2023-06-10 at 16 47 44](https://github.com/MalekBakary/App/assets/69464989/193023bb-c527-4616-8200-04fcf9028879)
how about now?

**Comment by eliasalbro95** [comment]
this is the max that we can do.
![Simulator Screen Shot - iPhone 14 Pro Max - 2023-06-12 at 19 47 25](https://github.com/MalekBakary/App/assets/69464989/2deea126-1bd9-4b84-a56b-8847180251b3)
