### ISSUE TITLE
مسح الكل بالفلتر

### ISSUE THREAD

**Issue by MalekBakary** [MalekBakary/App#10]
لما تشيل كل الاختيارات يلي اخترتها مسبقا مو ينشال تأثير الفلتر الا اذا كبست على مسح الكل

**Comment by eliasalbro95** [comment]
ما صارت معي هالمشكلة.. الوضع طبيعي

**Comment by MalekBakary** [comment]
رجع جرب المشكلة موجودة

**Comment by eliasalbro95** [comment]
you can test it next release, it's done.
