### ISSUE TITLE
الفرز بدل الرمز تبعها

### ISSUE THREAD

**Issue by MalekBakary** [MalekBakary/App#20]
كمان عمل a-z
Z-a
C-G
G-C
يعني تصاعدي وتنازلي

**Comment by eliasalbro95** [comment]
![Simulator Screen Shot - iPhone 14 Pro Max - 2023-06-12 at 19 16 20](https://github.com/MalekBakary/App/assets/69464989/d9afd26b-7591-462a-bbd9-985bda1aadc6)
how about now ?
