### ISSUE TITLE
الكوردات ماعم تطلع كل مرة

### ISSUE THREAD

**Issue by MalekBakary** [MalekBakary/App#33]
بصفحة الكوردات وكمان لما تكبس عالكورد بالترنيمة اغلب المرات مو يطلع الكورد ويطلع فاضي. مرات يطلع

**Comment by MalekBakary** [comment]
بس تحط اللايت مود

**Comment by eliasalbro95** [comment]
ما صارت معي المشكلة!! 
هلا ممكن يكون كتابة الكورد غلط .. بس بدي اشوف ايش عم يطلع اذا تعرف ترنيمة صارت فيها هالمشكلة بعتا

**Comment by eliasalbro95** [comment]
Chords library screen 
C# is the oppsite in Arabic
and the chords sometimes doesn't show when I go back from the screen and go in again.
