### ISSUE TITLE
تسجيل الدخول بصفحة الاعدادات عملها فقرة منفصلة لحالها

### ISSUE THREAD

**Issue by MalekBakary** [MalekBakary/App#44]
مثل يلي حطيتها بصفحة المجموعات تماما حطها

**Comment by eliasalbro95** [comment]
هيك قصدك؟؟
![photo_2023-09-02_11-16-07](https://github.com/MalekBakary/App/assets/69464989/7b9a116f-bcb9-4515-8f3f-bd16a3b68f7d)

**Comment by MalekBakary** [comment]
اي بس خليا فوق اذا مافي ازعاج
