### ISSUE TITLE
صفحة انشاء حساب

### ISSUE THREAD

**Issue by MalekBakary** [MalekBakary/App#45]
٢- بس تبعت ايميل تحقيق تظل علقان بالصفحة تبع الانيميشن يلي كلحطيته ومافي زر رجع لورا او زر الفاء او زر اعادة ارسال تفعيل 
٣- كلمة السر ما كلحطيت عليا شروط للقوة متل ما توماس عمل

**Comment by eliasalbro95** [comment]
إعادة إرسال الإيميل لازم توماس يعمل هالخيار عنده .. كتبت issue فيها ناطر خبر منه.
