### ISSUE TITLE
بس تعمل ترانسبوز لترنيمة جوات المجموعة يبقى الكورد القديم جنب اسم الترنيمة ومو يطلع الجديد

### ISSUE THREAD

**Issue by MalekBakary** [MalekBakary/App#48]

**Comment by MalekBakary** [comment]
اذا عدلت المفتاح من ال ٣ نقاط يتغير من برا بس الترنيمة مو يتغيروا كورداتها

**Comment by eliasalbro95** [comment]
وحدة وحدة .. الترانسبوز مؤقت هو مو شي اريد احفظه فا طبيعي تيرجع للسلم يلي اخترته وقت ضفت الترنيمة 
ال3 نقاط هاي Bug صح

**Comment by eliasalbro95** [comment]
add want to save edits for transpose dialog on back button and hard back button
