### ISSUE TITLE
الفلتر

### ISSUE THREAD

**Issue by MalekBakary** [MalekBakary/App#53]
اضافة كبسة تطبيق بالاضافة الى انه تتطبق الفلترة اذا نزلت البرداية

**Comment by eliasalbro95** [comment]
كل شهر برأي 😒

**Comment by MalekBakary** [comment]
لاتواخذني الله يخليك بس لما تجرب يكون الوضع مختلف... هلا قرار جديد كان انو الكبسة والبرداية مع بعض
