### ISSUE TITLE
رسالة الحذف

### ISSUE THREAD

**Issue by MalekBakary** [MalekBakary/App#55]
هل انت متأكد؟

وشيل المثلث الاصفر نزل من قيمة الابلكيشن

**Comment by eliasalbro95** [comment]
مالك ما عم اقرا افكارك على قولتك.. ايش بدك بالضبط تغير؟؟ الرسالة كلها ولا العربي بس ولا ايش بالضبط ؟
ومنشان موضوع المثلث ... هيك بدك تكون يعني؟

![photo_2023-09-03_20-04-58](https://github.com/MalekBakary/App/assets/69464989/0c9e573a-0801-461c-8c4b-97613b06aadd)

**Comment by MalekBakary** [comment]
اي هيك تمام بس العنوان تبع الرسالة عالجنب ونص الرسالة عالنص زبط هالفقرة وسكر الموضوع
