### ISSUE TITLE
المجموعات فاضية

### ISSUE THREAD

**Issue by MalekBakary** [MalekBakary/App#56]
شيل الحركة وخليا لون ابيض باهت متل الكلمة يلي تحت وشيل ال x o المهم بدون اخضر لان مبينة عنصر للكبس

**Comment by eliasalbro95** [comment]
تشيل ال x o  بس .. جربتا لون واحد منظرا شنيع ... ممكن نعطيا opacity يزبط الوضع

**Comment by eliasalbro95** [comment]
@MalekBakary شوفا

**Comment by eliasalbro95** [comment]
تيعمل مالك شي هو

**Comment by eliasalbro95** [comment]
اذا اوك سكّر الissue بطريقك
![photo_2023-09-05_20-14-38](https://github.com/MalekBakary/App/assets/69464989/9b1b6cfc-ee83-4f3c-b2d4-86f3f3a99dc1)
![photo_2023-09-05_20-14-36](https://github.com/MalekBakary/App/assets/69464989/d460f1c4-3947-4a09-a564-e33a4fce429c)

**Comment by MalekBakary** [comment]
خفف الشفافية ٢٠٪؜ كمان اذا تقدر

شيل النقطة بآخر الجملة
