### ISSUE TITLE
اضافة ترنيمة من ضمن السيت

### ISSUE THREAD

**Issue by MalekBakary** [MalekBakary/App#57]
شيل اشارة التعجب يلي تسأل بدك اضافة الترنيمة

**Comment by eliasalbro95** [comment]
ابش مشكلتك مع هالإشارات التعجب ؟؟🤣

**Comment by MalekBakary** [comment]
بشعين ويحسسوك انو عملت شي غلط وياخدوا كل الانتباه لهيك بلاهن احسن
