### ISSUE TITLE
اللوغو يلي يطلع اول ما تفتح الابلكيشن دقته واطية

### ISSUE THREAD

**Issue by MalekBakary** [MalekBakary/App#60]

**Comment by eliasalbro95** [comment]
اذا ع متحكي على يلي موجود بالفيديو يلي بواحد من الissues يلي كتبتها فا هاد من نظام الموبايل عندك ... عندي مو يطلع هاد .. يطلع شعار زامار كامل .. هيك .. بده تعديل بس رح يضل لآخر شي لأن شغله بالnative 

![photo_2023-09-03_20-29-06](https://github.com/MalekBakary/App/assets/69464989/b67c72c1-acb4-47bc-a5be-8afe079c302c)

**Comment by MalekBakary** [comment]
اي ترك الايشو مفتوح لكن

**Comment by eliasalbro95** [comment]
ممكن نعمله Animated بس بدها after effect .. أيش وضعك فيو؟ تتقدر تعملا؟
