### ISSUE TITLE
Reset

### ISSUE THREAD

**Issue by MalekBakary** [MalekBakary/App#61]
خلي ترجع الكورد للكي الاساسي

**Comment by eliasalbro95** [comment]
عم ترجعه ... اين المشكلة؟ 


https://github.com/MalekBakary/App/assets/69464989/0d9eec87-5c1e-44d9-846f-fca76b8a45ce

**Comment by MalekBakary** [comment]
اذا عملت ترانسبوز مو ترجعه

**Comment by eliasalbro95** [comment]
it is a backend issue related to this issue [List Change Song ](https://github.com/thomasdilts/churchsongs/issues/105)
