### ISSUE TITLE
لما تضيف مجموعة جديدة من صفحة المكتبة

### ISSUE THREAD

**Issue by MalekBakary** [MalekBakary/App#79]
مو تطلع المجموعة الجديدة الا اذا سكرت وفتحت

**Comment by eliasalbro95** [comment]
اين مو تطلع ؟؟ بشاشة الset??

**Comment by MalekBakary** [comment]
لا مو تطلع بين الستات يلي بنفس القائمة وانت لساتك جوات اضافة ترنيمة لمجموعة
